name: Build and Deploy ContactListAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Get directory
      run: ls

    - name: Build and Test
      run: |           
        dotnet restore backend/ContactListApi/ContactListApi.csproj
        dotnet build backend/ContactListApi/ContactListApi.csproj --configuration Release
        dotnet test backend/ContactListApi/ContactListApi.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get directory
      run: ls

    - name: Deploy to Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      working-directory: ./backend/ContactListApi
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker-compose up -d
                          
                          