name: Build and Deploy ContactListAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Build and Test
      run: |
        dotnet restore backend/ContactListApi/ContactLisApi.csproj
        dotnet build backend/ContactListApi/ContactLisApi.csproj --configuration Release
        dotnet test backend/ContactListApi/ContactLisApi.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker-compose -f backend/ContactLisApi/docker-compose.yml up -d
                          